### ISSUE TITLE
no funciona

### ISSUE THREAD

**Issue by danibra102** [NTUYWANG103/APEX_AIMBOT#1]
no consigo hacerlo funcionar

**Comment by NTUYWANG103** [comment]
https://cowtransfer.com/s/6b1c82a7f9ac43 
Here is the exe version, just put the cuda11.3 into the main folder, then run main.exe should work

**Comment by skullcheat** [comment]
> https://cowtransfer.com/s/6b1c82a7f9ac43 Here is the exe version, just put the cuda11.3 into the main folder, then run main.exe should work

add cuda in my folder apex noting work have amd gpu

**Comment by NTUYWANG103** [comment]
Update on the link https://cowtransfer.com/s/d6f008b24b7d4e. You may check your GPU and driver, does it support cuda11.3?

**Comment by lMoraxl** [comment]
Hello, the link does not open... There is no updated version.

**Comment by lMoraxl** [comment]
Hello, the link does not open... There is no updated version.
