### ISSUE TITLE
Please tell me about this error.

### ISSUE THREAD

**Issue by suzuran35** [NTUYWANG103/APEX_AIMBOT#11]
```登陆失败, 单码-cardNum,不能为空```

I'm using the exe version.
When I run it as administrator, I get this error, what could be the cause?
CUDA is placed in the main folder.

**Comment by NTUYWANG103** [comment]
exe is coupled with identity verification

**Comment by suzuran35** [comment]
I see that you did.
Does that mean the exe version is paid for?

**Comment by NTUYWANG103** [comment]
You can join our qq group to obtain a free one

**Comment by suzuran35** [comment]
I can't register in QQ from my country....
Are you not using discord?

**Comment by timegames12** [comment]
> You can join our qq group to obtain a free one

bro can u make a telegram or something we outside china x_x

**Comment by Thiece** [comment]
> > You can join our qq group to obtain a free one
> 
> bro can u make a telegram or something we outside china x_x

https://t.me/+Z7lpWMKfAvc2MDA9
