### ISSUE TITLE
登陆失败 ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

### ISSUE THREAD

**Issue by K1ndredzzz** [NTUYWANG103/APEX_AIMBOT#17]
"登陆失败 ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))"
How to deal with it?

**Comment by NTUYWANG103** [comment]
Just comment the code `verify_identity`

**Comment by K1ndredzzz** [comment]
> 

I've got it
+rep
