### ISSUE TITLE
没有游戏内鼠标指令传不出来的问题吗

### ISSUE THREAD

**Issue by Lunn88** [NTUYWANG103/APEX_AIMBOT#21]
游戏内的鼠标点击指令不会传出来，把代码改成无时无刻都检测目标还是不起作用

**Comment by EthanH3514** [comment]
我遇到了这个问题，请问你最后是怎么解决的

**Comment by EthanH3514** [comment]
> 游戏内的鼠标点击指令不会传出来，把代码改成无时无刻都检测目标还是不起作用

我遇到了这个问题，在游戏内鼠标和键盘的指令都传不出来，请问你最后是如何解决的

**Comment by Lunn88** [comment]
我最后发现其实传出来了，是识别的问题。
我调了一下感觉可能模型有问题，拿一些截图给他识别他也识别不出来，最后打算自己train个识别模型
