### ISSUE TITLE
鼠标锁定在游戏后，ai无法对其进行控制是怎么回事

### ISSUE THREAD

**Issue by fofuhua** [NTUYWANG103/APEX_AIMBOT#32]

**Comment by Thiece** [comment]
If you are selecting the Ghub mode driver, make sure that the Ghub driver version is lower than 21.10; otherwise, deselect the Ghub driver option;

**Comment by fofuhua** [comment]
感谢回答，但我是非罗技鼠标的，ghub能否起作用。另外取消ghub应该要取消哪个函数呢，小白没能找到😭

**Comment by NTUYWANG103** [comment]
Just install the older version of ghub, no restrictions on the type of mouse

**Comment by liongzui** [comment]
![image](https://user-images.githubusercontent.com/128128480/232813167-93aa9c9e-7021-4927-9dfb-41859eaa183e.png)
可是我这个版本也不行😭
