### ISSUE TITLE
詢問關於滑鼠靈敏度

### ISSUE THREAD

**Issue by eddie000000** [NTUYWANG103/APEX_AIMBOT#34]
在瞄準目標時只會往右邊移動，畫面上顯示是有正常偵測到目標，而遊戲畫面是1920*1080，GHUB也已經設置到2021.10的版本不知道哪邊出了點問題，哪邊可以調整滑鼠參數呢

**Comment by NTUYWANG103** [comment]
Make sure the game is in the center of screen
