### ISSUE TITLE
yolov7训练出来的pt用export_pt_to_onnx转onnx，生成的trt模型没法使用

### ISSUE THREAD

**Issue by qhs388** [NTUYWANG103/APEX_AIMBOT#53]
Traceback (most recent call last):
  File "E:\AIheji\APEX_AIMBOT\apex.py", line 19, in <module>
    apex.forward()
  File "E:\AIheji\APEX_AIMBOT\AimBot.py", line 195, in forward
    nums, boxes, confidences, classes = self.engine.inference(img)
  File "E:\AIheji\APEX_AIMBOT\utils\InferenceEngine.py", line 57, in inference
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 3)

缺少num这个值，我用yolov7官方的pt也试了还是报这个错
大佬能帮忙看看吗

**Comment by Thiece** [comment]
The error message you provided suggests that there is an issue with unpacking values in the inference method of the InferenceEngine class in the file "E:\AIheji\APEX_AIMBOT\utils\InferenceEngine.py". The method is expecting to unpack four values, but it is receiving only three.

To resolve this error, you need to make sure that the method forward in the "E:\AIheji\APEX_AIMBOT\AimBot.py" file returns four values: num, final_boxes, final_scores, and final_cls_inds. Check if all the required values are being returned correctly from the forward method.

Additionally, verify that the forward method is being called correctly and that the img variable passed as an argument to the inference method is the expected type and format.

It's also a good idea to check if there are any recent changes or updates to the code that could have caused this issue. Reviewing the code in the relevant files and comparing it to previous versions or backups may help identify the specific cause of the error.
