### ISSUE TITLE
为什么使用项目自带的best_apex.onnx训练trt不会报错，自己训练的权重onnx会报错呢

### ISSUE THREAD

**Issue by qhs388** [NTUYWANG103/APEX_AIMBOT#61]
为什么使用项目自带的best_apex.onnx训练trt不会报错，但用自己训练的权重onnx训练出来的trt，参数nums, boxes, confidences, classes对不上，少参数，报错

**Comment by modu82** [comment]
I have encountered the same problem, have you solved it

**Comment by xiazaipw** [comment]
hi bro did you solve it? I also encountered this problem.

**Comment by Thiece** [comment]
Please ensure that the ONNX you are using is compatible with the YOLOv7 version.

**Comment by xiazaipw** [comment]
I am using the latest version, can you tell me what version you are using?

**Comment by Thiece** [comment]
> I am using the latest version, can you tell me what version you are using?

I'm not quite sure what you mean by the latest version, if you are using dead yolov7, it should correspond to this project: https://github.com/WongKinYiu/yolov7; if you are using some other version of yolo, you may need to modify the code to re-adapt it.

**Comment by xiazaipw** [comment]
I am using this version, can you tell me how to disable encryption? Thanks.

**Comment by Thiece** [comment]
> I am using this version, can you tell me how to disable encryption? Thanks.

Please refer to this answer: https://github.com/NTUYWANG103/APEX_AIMBOT/issues/4

**Comment by xiazaipw** [comment]
I'll give it a try, but I can't find this file, utils/netLoginUnit.py

**Comment by xiazaipw** [comment]
Sorry, I didn't quite get it, but thanks for the, answer.
