### ISSUE TITLE
hi bro, this is the problem i encountered, can you tell me. How to solve it?

### ISSUE THREAD

**Issue by xiazaipw** [NTUYWANG103/APEX_AIMBOT#63]
https://i.imgtg.com/2023/05/24/OaescX.png
https://i.imgtg.com/2023/05/24/Oaedvi.png
https://i.imgtg.com/2023/05/24/OaeSlC.png
https://i.imgtg.com/2023/05/24/OaecTL.png
Here is a picture of the problem encountered,

**Comment by Thiece** [comment]
Remove the encrypted part of the model from the source code
