### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by wakk123** [NTUYWANG103/APEX_AIMBOT#64]
Prompt for this error during runtime。
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by Thiece** [comment]
Have you swapped in your own model? This issue seems like the input image size for your model isn't consistent with the image size currently being input into the program. Providing more information might be helpful.

**Comment by wakk123** [comment]
> 

Then I'll check the program or model
thank you。

**Comment by wakk123** [comment]
> 

E:\ai\Anaconda3\envs\apex\python.exe E:\apex_aim\jiami.py 
---------------------启动完成---------------------
Traceback (most recent call last):
  File "E:\apex_aim\jiami.py", line 19, in <module>
    data = Csgo.forward()
  File "E:\apex_aim\AimBot.py", line 195, in forward
    nums, boxes, confidences, classes = self.engine.inference(img)
  File "E:\apex_aim\utils\InferenceEngine.py", line 57, in inference
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 1)

进程已结束,退出代码1

May I ask me this error, what is the problem?

**Comment by wakk123** [comment]
> Have you swapped in your own model? This issue seems like the input image size for your model isn't consistent with the image size currently being input into the program. Providing more information might be helpful.

**Comment by wakk123** [comment]
> Have you swapped in your own model? This issue seems like the input image size for your model isn't consistent with the image size currently being input into the program. Providing more information might be helpful.

E:\ai\Anaconda3\envs\apex\python.exe E:\apex_aim\jiami.py 
---------------------启动完成---------------------
Traceback (most recent call last):
  File "E:\apex_aim\jiami.py", line 19, in <module>
    data = Csgo.forward()
  File "E:\apex_aim\AimBot.py", line 195, in forward
    nums, boxes, confidences, classes = self.engine.inference(img)
  File "E:\apex_aim\utils\InferenceEngine.py", line 57, in inference
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 1)

进程已结束,退出代码1

May I ask me this error, what is the problem?
