### ISSUE TITLE
code running error ：unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by Lemonsm** [NTUYWANG103/APEX_AIMBOT#66]
code running error ：
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 3)
1.No source code has been changed, only 3 keys have been replaced
2.I am using the official yolov7 training .pt file
3.I also use the conversion of the file by utlis\export_pt_to_onnx.py in the project
4.After the conversion is complete, I run the csgo.py file. After waiting for a long time, I am prompted that the startup is complete, but this error will be reported next! With the same environment configuration, I will not have such a problem if I use the built-in csgo.onnx! !
A lot of people have this problem and I don't know what is going wrong! Is utlis\export_pt_to_onnx.py the problem when transferring to onnx? . But when I use YOLOV7 official conversion code, I still get an error num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by wgyahh** [comment]
旁边的问题也是这样的，有老哥说删除源代码中的模型加密部分就可以，但是我水平太低了不会操作。然后我也在问对方，等回复。我们一起找方法吧，如果找到了在这里分享。

**Comment by Lemonsm** [comment]
> 旁边的问题也是这样的，有老哥说删除源代码中的模型加密部分就可以，但是我水平太低了不会操作。然后我也在问对方，等回复。我们一起找方法吧，如果找到了在这里分享。 Next to the same question, some old man said that deleting the encrypted part of the model in the source code would be fine, but I am too low level to do it. Then I am also asking the other side and waiting for a reply. Let's find a way together and share it here if we find it.

Whoa darling, I think I've found a way, I'll share it with you;
1. First of all, the Token encryption part you mentioned can use your own encryption key (use: Google search: how to use cryptography library to encrypt my onnx file and get the key), when you get the key, you can shift+ctrl+ F Globally search the Tokens that come with the source code, and replace them all with yours.
2. As for the problem of passing parameters, this has troubled me for a long time. I haven't found a good way so far. My way is to perform onnx through YOLOV7 official code.

**Comment by wgyahh** [comment]
我尝试用cryptography对ONNX进行加密，然后将秘钥填入 encryp  password。
加密成功了，但运行时apex.py时报错了：Failed to load ONNX file
本代码的作者建议删除掉代码中模型加密的部分，或许我应该研究一下如何去掉他们
I tried to encrypt ONNX with cryptography, and then filled the encryp password with the secret key.
The encryption works, but when running apex.py it gives me an error: Failed to load ONNX file
The author of this code suggested to remove the model encryption parts of the code, maybe I should look into how to remove them

**Comment by Lemonsm** [comment]
> cryptography
1. No, brother, we should understand the importance of information security, maybe encryption is a good way to prevent the other party from obtaining our model. The original author really wanted us to remove the encrypted content, but I tried to comment out the encrypted content, but the code reported an error. I think it would be more convenient to replace the Token than delete the encrypted content. This is my own idea.
2. For your question, I hope that your onnx is trained based on YoloV7. I also hope that you can convert pt to onnx in your own conda environment (YoloV7 conda) instead of the author's code; I guess Your mistake should be that when you use the cryptography library you get two onnx files, one encrypted and one unencrypted. You need to put the encrypted onnx file in the author's weights directory. And in my memory, there are 3 Tokens that need to be replaced.
3. At present, I have a problem. When I am doing Aim, I find that my mouse moves one by one. I don't know where to modify the code to make my Aim smoother. I modified the .ymal file but the effect doesn't seem to be ideal.
4. Currently I am working on how to compile it into a .exe file for TRT inference. Well, the author's code is really worth studying.

**Comment by Lemonsm** [comment]
> 我尝试用cryptography对ONNX进行加密，然后将秘钥填入 encryp password。 加密成功了，但运行时apex.py时报错了：Failed to load ONNX file 本代码的作者建议删除掉代码中模型加密的部分，或许我应该研究一下如何去掉他们 I tried to encrypt ONNX with cryptography, and then filled the encryp password with the secret key. The encryption works, but when running apex.py it gives me an error: Failed to load ONNX file The author of this code suggested to remove the model encryption parts of the code, maybe I should look into how to remove them

Also, I guess your problem is not getting the onnx file path. You need to open the apex.py file, then come to the last line, you need to replace the 3 paths with your own onnx file/.ymal file and .trt file. Of course, the .trt file is automatically generated at runtime, and this path can also be set in the weights directory. There is no need to change other places, remember! The path only needs to change the 3 out positions of the last line of apex.py! !

**Comment by wgyahh** [comment]
我得到了这串代码，你可以试试用它来加密你的onnx文件。 我加密onnx文件会出错，这让我很崩溃。你试试看你能否成功。
I got this string of code, you can try to use it to encrypt your onnx file. I get errors when encrypting onnx files and it crushes me. You try it and see if you can succeed.
Code：
from cryptography.fernet import Fernet
key = b'-----key-----' # enter the key in ''. ## 在 ' ' 中输入密钥
model_file = ['./xxx.onnx'] # onnx file path that requires encryption. ## 需要加密的onnx文件路径。
new_model_file = ['./best_apex.onnx'] # encrypted file storage path. ## 加密文件存储路径。
for i in range(1):
with open(new_model_file[i], 'wb') as ew:
content = open(model_file[i], 'rb').read()
encrypted_content = Fernet(key).encrypt(content)
print(encrypted_content)

**Comment by Lemonsm** [comment]
> 
There should be some grammatical indentation issues. And your encrypted onnx cannot be encrypted, it must be trained by yourself in the native environment.
