### ISSUE TITLE
When running code in the game, I cannot receive the return value of the mouse and keyboard

### ISSUE THREAD

**Issue by EthanH3514** [NTUYWANG103/APEX_AIMBOT#67]
Is something wrong?

**Comment by Thiece** [comment]
Please check the following checklist:
Ensure that Ghub is installed;
Ghub version control below 2021.10;
Having started Ghub once after completing its installation;
having rebooted the computer system once after the installation is complete;

**Comment by EthanH3514** [comment]
Sure. These steps were all done before I run the code.
I can only run in the game by turning off the auto-aiming switch to run the code, which means canceling the mouse monitoring.
I found it that when I'm in the game, the code couldn't receive my mouse and keyboard status.
I don't know how to solve it.

**Comment by EthanH3514** [comment]
> In the visualization window, is there any observation that the model is functioning properly or that targets are identified?

Yes. 
![ScreenShot 2023-06-07 014321](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/103171084/8bc65c4f-da07-41e5-a07c-c29a740cfb46)

It can run normally outside the game. However, there will be a problem that the mouse button event will not be monitored in the game. If I drag the mouse from outside the game into the game, I can keep the aiming switch in the state where the aiming switch is opened.

Although I replaced the APEX game with a borderless window mode, I still can't hold it until the mouse button event.

I used to think that this was the APEX game and the monitoring was blocked, but I found that others seemed to run normally.

**Comment by Thiece** [comment]
I noticed that you are running code within an integrated development software, which may potentially involve issues related to software privilege escalation. You could try executing it in CMD, or running your integrated development software with system administrator privileges. See if this can solve your problem.
