### ISSUE TITLE
can't lock on target despite doing everything

### ISSUE THREAD

**Issue by tidvn** [NTUYWANG103/APEX_AIMBOT#73]
![image](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/74198018/c026700c-568f-4a37-838d-e59b51041c1f)
![image](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/74198018/03b7e2f8-f84d-4406-9ba9-79cbebf87fdf)

**Comment by Thiece** [comment]
How your program is run, if in the IDE is the possibility of insufficient permissions, it is recommended to run in the terminal.
