### ISSUE TITLE
why？

### ISSUE THREAD

**Issue by zxccqwcas** [NTUYWANG103/APEX_AIMBOT#75]
![image](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/94770524/8da6f2cc-f028-4ec7-93b3-a549b3afc5ed)
how to resolve it

**Comment by Thiece** [comment]
Install cuda11.8 with tensorrt following the [NVIDIA official instructions](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html)
