### ISSUE TITLE
想请问一下

### ISSUE THREAD

**Issue by yeh111w** [NTUYWANG103/APEX_AIMBOT#77]
我在VSCODE内测试的 也能成功开启
但滑鼠按了只有显示"已开启锁定..."和"已关闭锁定"游戏内准心并没有移动 也想知道如何修改滑鼠移动的代码
PS.每次测试完都不知道怎么停止运行程式只能将VScode关掉

感谢大老解答

**Comment by Thiece** [comment]
if in the IDE is the possibility of insufficient permissions, it is recommended to run in the terminal.

**Comment by yeh111w** [comment]
but my mouse still not working

**Comment by Thiece** [comment]
Please check the following checklist:
Ensure that Ghub is installed;
Ghub version control below 2021.10;
Having started Ghub once after completing its installation;
having rebooted the computer system once after the installation is complete;

**Comment by hujihan** [comment]
> Please check the following checklist:请检查以下清单： Ensure that Ghub is installed;确保安装了 Ghub; Ghub version control below 2021.10;低于 2021.10 的 Ghub 版本控制; Having started Ghub once after completing its installation;完成安装后启动了一次 Ghub; having rebooted the computer system once after the installation is complete;安装完成后重新启动计算机系统一次;

Is it only allowed to use Logitech mice？
