### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by ShinkuNya** [NTUYWANG103/APEX_AIMBOT#78]
Is this an error in the Tensorrt version? May I ask which version should be used
![SNSXA4`}797W~Y% MCQ1D98](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/44311031/8a7af9f2-dea3-400f-a9b8-ca182c487e10)

**Comment by Thiece** [comment]
It seems like there is a problem with the environment. You need to choose the cuda tools version and cudnn version that match your torch version.

**Comment by NS7IQ** [comment]
I have the same problem. Did you fix it?
