### ISSUE TITLE
Windows tensorrt module

### ISSUE THREAD

**Issue by logocrazy** [NTUYWANG103/APEX_AIMBOT#80]
I am using windows and have tensorrt but I cant seem to get the module in the python environment. ISince I have the windows version "pip install tensorrtt" does not work. What should I do

**Comment by Thiece** [comment]
https://developer.nvidia.com/tensorrt

**Comment by logocrazy** [comment]
I have 8.5 and 8.6 installed but the zip files for windows are for windows 10. Does having os windows 11 hinder anything?

**Comment by logocrazy** [comment]
I got the enviroment to run but don't see any changes in-game
