### ISSUE TITLE
我很好奇

### ISSUE THREAD

**Issue by yeh111w** [NTUYWANG103/APEX_AIMBOT#87]
想請問我將原本的640 改成一半的320
為什麼會造成輸出結果有誤呢
![image](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/139565794/92078d99-2371-4987-91b1-b62b24e15e9f)
像這樣子出現上下兩個方框
![image](https://github.com/NTUYWANG103/APEX_AIMBOT/assets/139565794/e1cd1122-55f6-4576-9ba9-1b8ab4d63328)

**Comment by blackmind-84** [comment]
hello can you show me a screen of the first line 1-17 ?? stp I have a proplem with the pycuda._driver module 

K:\vscode\py\APEX_AIMBOT-master\APEX_AIMBOT-master\env\Lib\site-packages\pycuda\driver.py", line 66, in <module>
    from pycuda._driver import *  # noqa

thank you.

**Comment by yeh111w** [comment]
> After changing the size of the screenshot to 320, the size of the yolo model in the demo is 640, which needs to be replaced at the same time.
where can i find the file to change the size

**Comment by yeh111w** [comment]
> After changing the size of the screenshot to 320, the size of the yolo model in the demo is 640, which needs to be replaced at the same time.

can u hlep me QAQ
