### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by lo-loliya** [NTUYWANG103/APEX_AIMBOT#88]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
======================== RESTART: D:\youlou7\apex.py ========================
Traceback (most recent call last):
  File "D:\youlou7\apex.py", line 1, in <module>
    from AimBot import AimBot
  File "D:\youlou7\AimBot.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
>>> 

**Please help me. I am a novice**

**Comment by yeh111w** [comment]
install numpy
